// <auto-generated />
using David__Dawson_Assignment_3.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace David__Dawson_Assignment_3.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20220327025308_Mig01")]
    partial class Mig01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.Company", b =>
                {
                    b.Property<int>("companyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("companyID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("companyID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.CompanyGameDevelopment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyID")
                        .HasColumnType("int");

                    b.Property<int>("gameID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("companyID");

                    b.HasIndex("gameID");

                    b.ToTable("CompanyGameDevelopment");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.Game", b =>
                {
                    b.Property<int>("gameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameID"), 1L, 1);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gameID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.CompanyGameDevelopment", b =>
                {
                    b.HasOne("David__Dawson_Assignment_3.Models.Entities.Company", "Company")
                        .WithMany("CompanyBudget")
                        .HasForeignKey("companyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("David__Dawson_Assignment_3.Models.Entities.Game", "Game")
                        .WithMany("GameBudget")
                        .HasForeignKey("gameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.Company", b =>
                {
                    b.Navigation("CompanyBudget");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.Game", b =>
                {
                    b.Navigation("GameBudget");
                });
#pragma warning restore 612, 618
        }
    }
}
