// <auto-generated />
using David__Dawson_Assignment_3.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace David__Dawson_Assignment_3.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20220329225102_Mig01")]
    partial class Mig01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.Game", b =>
                {
                    b.Property<int>("gameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameID"), 1L, 1);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gameID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.Person", b =>
                {
                    b.Property<int>("personID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.PersonGame", b =>
                {
                    b.Property<int>("personGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personGameID"), 1L, 1);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("gameID")
                        .HasColumnType("int");

                    b.Property<int>("personID")
                        .HasColumnType("int");

                    b.HasKey("personGameID");

                    b.HasIndex("gameID");

                    b.HasIndex("personID");

                    b.ToTable("PersonGame");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.PersonGame", b =>
                {
                    b.HasOne("David__Dawson_Assignment_3.Models.Entities.Game", "Game")
                        .WithMany("PersonRating")
                        .HasForeignKey("gameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("David__Dawson_Assignment_3.Models.Entities.Person", "Person")
                        .WithMany("GameRating")
                        .HasForeignKey("personID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.Game", b =>
                {
                    b.Navigation("PersonRating");
                });

            modelBuilder.Entity("David__Dawson_Assignment_3.Models.Entities.Person", b =>
                {
                    b.Navigation("GameRating");
                });
#pragma warning restore 612, 618
        }
    }
}
